//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bai6_23TH2519.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NhanVien
    {
        public int id_NV { get; set; }
        public string HoNV { get; set; }
        public string TenNV { get; set; }
        public Nullable<bool> GioiTinh { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime NgaySinh { get; set; }

        [DisplayFormat(DataFormatString = "{0:N0} VNĐ")]
        public Nullable<decimal> Luong { get; set; }
        public byte[] AnhNV { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> id_PhongBan { get; set; }

        public virtual PhongBan PhongBan { get; set; }
    }
}
